Algoritmo "ex2"
// 
//Faça um algoritmo que receba dois números e ao final mostre a
// soma, subtração, multiplicação e a divisão dos números lidos.
Var
n1, n2: real

Inicio
escreva("Digite um n°: ")
leia(n1)
escreva("Digite outro nº: ")
leia(n2)

escreval("n1 + n2 = ",n1 + n2)
escreval("n1 - n2 = ",n1 - n2)
escreval("n1 / n2 = ",n1 / n2)
escreval("n1 * n3 = ",n1 * n2)
escreval("")
escreval("Essas são as operaçoes")

Fimalgoritmo