Algoritmo "ex3"
// Função : Escrever um algoritmo para determinar o consumo médio de um
// automóvel sendo fornecida a distância total percorrida pelo automóvel e
// o total de combustível gasto
Var
gasosa, dis, m: real


Inicio
escreva("Digite a distância percorrida: ")
leia (dis)
escreva("Digite o consumo de gasolina: ")
leia (gasosa)

m <- (dis + gasosa) / 2

escreval("Consumo medio do combustivel: ", m)


Fimalgoritmo